apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    version: "1"
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: leopoldox3/avatares-devops-web:v1
          ports:
            - containerPort: 5173
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
        - name: prometheus-exporter
          image: prom/node-exporter:v1.8.2
          ports:
            - containerPort: 9101
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "125m"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
