apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    version: "1"
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: leopoldox3/avatares-devops-api:v1
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        - name: prometheus-exporter
          image: prom/statsd-exporter:v0.28.0
          ports:
            - containerPort: 9102
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
