apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: web-port
      port: 5173 # Puerto lógico del servicio
      targetPort: 5173 # Puerto del contenedor
      nodePort: 32000 # Puerto expuesto al exterior
    - name: web-metrics
      port: 9100 # Puerto lógico del servicio para métricas
      targetPort: 9100 # Puerto del sidecar container
      nodePort: 32003 # Puerto expuesto al exterior para métricas
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - name: api-port
      port: 5000 # Puerto lógico del servicio
      targetPort: 5000 # Puerto del contenedor
      nodePort: 32005 # Puerto expuesto al exterior
    - name: api-metrics
      port: 9102 # Puerto lógico del servicio para métricas
      targetPort: 9102 # Puerto del sidecar container
      nodePort: 32006 # Puerto expuesto al exterior para métricas

